# Generated by Django 5.2 on 2025-07-09 01:18

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Celular completo', max_length=15, unique=True, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Email completo', max_length=254, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corretores.pessoa')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='corretores', variations={}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Corretor',
                'verbose_name_plural': 'Corretores',
            },
            bases=('corretores.pessoa',),
        ),
    ]
