# Generated by Django 5.2 on 2025-07-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0002_corretor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='fone',
            field=models.CharField(help_text='Celular completo do corretor', max_length=15, unique=True, verbose_name='Telefone'),
        ),
    ]
