# Generated by Django 5.2 on 2025-07-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0003_alter_corretor_fone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='email',
            field=models.EmailField(help_text='Email completo do corretor', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='nome',
            field=models.CharField(help_text='Nome completo do corretor', max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
