# Generated by Django 5.2 on 2025-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0004_alter_corretor_email_alter_corretor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='nome',
            field=models.CharField(help_text='Nome completo do corretor', max_length=100, verbose_name='Nome'),
        ),
    ]
