# Generated by Django 5.2 on 2025-05-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000000, verbose_name='Valor da transação'),
        ),
    ]
