# Generated by Django 5.2 on 2025-06-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_celular_cliente_fone'),
        ('imoveis', '0007_remove_imovel_proprietario'),
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Imóvel do proprietário', 'verbose_name_plural': 'Imóveis do proprietário'},
        ),
        migrations.AddField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000000, verbose_name='Valor da transação'),
        ),
        migrations.AlterUniqueTogether(
            name='transacao',
            unique_together={('imovel', 'cliente', 'tipo')},
        ),
    ]
