# Generated by Django 5.2 on 2025-05-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_celular_cliente_fone'),
        ('imoveis', '0006_delete_proprietariosimovel'),
        ('transacoes', '0002_transacao_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Imóvel do proprietário', 'verbose_name_plural': 'Imóveis do proprietário'},
        ),
        migrations.AlterUniqueTogether(
            name='transacao',
            unique_together={('imovel', 'cliente', 'tipo')},
        ),
    ]
