# Generated by Django 5.2 on 2025-07-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_celular_cliente_fone'),
        ('imoveis', '0009_imovel_valor_aluguel_imovel_valor_venda'),
        ('transacoes', '0003_alter_transacao_valor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transacao',
            unique_together={('imovel', 'cliente')},
        ),
    ]
