# Generated by Django 5.2 on 2025-07-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0004_alter_transacao_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor da comissão'),
        ),
    ]
