# Generated by Django 5.2 on 2025-07-09 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('corretores', '0001_initial'),
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(verbose_name='Data e Hora da visita')),
                ('observacoes', models.TextField(blank=True)),
                ('situacao', models.CharField(blank=True, choices=[('A', 'Agendada'), ('CA', 'Cancelada'), ('CO', 'Concluída')], default='A', max_length=100, verbose_name='Situação da visita')),
                ('cliente', models.ForeignKey(default='', help_text='Nome do cliente', on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='clientes.cliente', verbose_name='Cliente')),
                ('corretor', models.ForeignKey(default='', help_text='Nome do corretor', on_delete=django.db.models.deletion.CASCADE, related_name='corretor', to='corretores.corretor', verbose_name='Corretor')),
                ('imovel', models.ForeignKey(default='', help_text='Código Único do Imóvel', on_delete=django.db.models.deletion.CASCADE, related_name='imovel', to='imoveis.imovel', verbose_name='Imóvel')),
            ],
        ),
    ]
