# Generated by Django 5.2 on 2025-04-30 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_celular_cliente_fone'),
        ('corretores', '0002_corretor_foto'),
        ('imoveis', '0003_imovel_proprietario'),
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='cliente',
            field=models.ForeignKey(default='', help_text='Nome do cliente', on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='clientes.cliente', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='visita',
            name='corretor',
            field=models.ForeignKey(default='', help_text='Nome do corretor', on_delete=django.db.models.deletion.PROTECT, related_name='corretor', to='corretores.corretor', verbose_name='Corretor'),
        ),
        migrations.AddField(
            model_name='visita',
            name='data_hora',
            field=models.DateTimeField(default='0001-01-01 00:00'),
        ),
        migrations.AddField(
            model_name='visita',
            name='imovel',
            field=models.ForeignKey(default='', help_text='Código Único do Imóvel', on_delete=django.db.models.deletion.PROTECT, related_name='imovel', to='imoveis.imovel', verbose_name='Imóvel'),
        ),
        migrations.AddField(
            model_name='visita',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
