# Generated by Django 5.2 on 2025-04-30 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0002_visita_cliente_visita_corretor_visita_data_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data_hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 20, 50, 13, 470755)),
        ),
    ]
