# Generated by Django 5.2 on 2025-04-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0003_alter_visita_data_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='data_hora',
        ),
    ]
