# Generated by Django 5.2 on 2025-04-30 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0004_remove_visita_data_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='data_hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 20, 54, 37, 108816)),
        ),
    ]
