# Generated by Django 5.2 on 2025-05-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0011_alter_visita_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data_hora',
            field=models.DateTimeField(verbose_name='Data e Hora da visita'),
        ),
    ]
