# Generated by Django 5.2 on 2025-05-01 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_celular_cliente_fone'),
        ('visita', '0012_alter_visita_data_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='data_hora',
            new_name='datahora',
        ),
        migrations.AlterField(
            model_name='visita',
            name='cliente',
            field=models.ForeignKey(default='', help_text='Nome do cliente', on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
