# Generated by Django 5.2 on 2025-05-15 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_celular_cliente_fone'),
        ('corretores', '0002_corretor_foto'),
        ('imoveis', '0004_alter_imovel_proprietario'),
        ('visita', '0013_rename_data_hora_visita_datahora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='cliente',
            field=models.ForeignKey(default='', help_text='Nome do cliente', on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='corretor',
            field=models.ForeignKey(default='', help_text='Nome do corretor', on_delete=django.db.models.deletion.CASCADE, related_name='corretor', to='corretores.corretor', verbose_name='Corretor'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='imovel',
            field=models.ForeignKey(default='', help_text='Código Único do Imóvel', on_delete=django.db.models.deletion.CASCADE, related_name='imovel', to='imoveis.imovel', verbose_name='Imóvel'),
        ),
    ]
