# Generated by Django 5.2 on 2025-05-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0014_alter_visita_cliente_alter_visita_corretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='situacao',
            field=models.CharField(blank=True, choices=[('A', 'Agendada'), ('CA', 'Cancelada'), ('CO', 'Concluída')], max_length=100, verbose_name='Situação da visita'),
        ),
    ]
