# Generated by Django 5.2 on 2025-07-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0015_visita_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='situacao',
            field=models.CharField(blank=True, choices=[('A', 'Agendada'), ('CA', 'Cancelada'), ('CO', 'Concluída')], default='A', max_length=100, verbose_name='Situação da visita'),
        ),
    ]
