# Generated by Django 5.2 on 2025-07-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='proprietarios',
            field=models.ManyToManyField(related_name='imoveis', to='proprietarios.proprietario', verbose_name='Proprietários'),
        ),
    ]
