# Generated by Django 5.2 on 2025-04-30 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_initial'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(default='', help_text='Nome do Proprietário', on_delete=django.db.models.deletion.PROTECT, related_name='proprietario', to='proprietarios.proprietario', verbose_name='Proprietário'),
        ),
    ]
