# Generated by Django 5.2 on 2025-05-15 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_proprietario'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(default='', help_text='Nome do Proprietário', on_delete=django.db.models.deletion.CASCADE, related_name='proprietario', to='proprietarios.proprietario', verbose_name='Proprietário'),
        ),
    ]
