# Generated by Django 5.2 on 2025-05-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_proprietariosimovel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProprietariosImovel',
        ),
    ]
