# Generated by Django 5.2 on 2025-06-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_delete_proprietariosimovel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='proprietario',
        ),
    ]
