# Generated by Django 5.2 on 2025-07-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_remove_imovel_proprietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='tipo_transacao',
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_aluguel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_venda',
            field=models.BooleanField(default=False),
        ),
    ]
