# Generated by Django 5.2 on 2025-07-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_remove_imovel_tipo_transacao_imovel_tipo_aluguel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='valor_aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
