# Generated by Django 5.2 on 2025-07-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_imovel_valor_aluguel_imovel_valor_venda'),
        ('proprietarios', '0008_alter_proprietario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='proprietarios',
            field=models.ManyToManyField(related_name='imoveis', to='proprietarios.proprietario', verbose_name='Proprietários'),
        ),
    ]
