# Generated by Django 5.2 on 2025-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_email_alter_cliente_fone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(help_text='Nome completo do cliente', max_length=100, verbose_name='Nome'),
        ),
    ]
