# Generated by Django 5.2 on 2025-07-09 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corretores', '0001_initial'),
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corretores.pessoa')),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
            },
            bases=('corretores.pessoa',),
        ),
        migrations.CreateModel(
            name='ImoveisProprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imovel', models.ForeignKey(help_text='Imóvel', on_delete=django.db.models.deletion.CASCADE, related_name='imovelprop', to='imoveis.imovel', verbose_name='Imovel')),
                ('proprietario', models.ForeignKey(help_text='Nome do proprietario', on_delete=django.db.models.deletion.CASCADE, related_name='proprietarioimov', to='proprietarios.proprietario', verbose_name='Proprietario')),
            ],
            options={
                'verbose_name': 'Imóvel do proprietário',
                'verbose_name_plural': 'Imóveis do proprietário',
                'unique_together': {('proprietario', 'imovel')},
            },
        ),
    ]
