# Generated by Django 5.2 on 2025-05-21 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_delete_proprietariosimovel'),
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImoveisProprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imovel', models.ForeignKey(help_text='Propriedades do imóvel', on_delete=django.db.models.deletion.PROTECT, related_name='imovelproprietario', to='imoveis.imovel', verbose_name='Imóvel')),
                ('proprietario', models.ForeignKey(help_text='Nome do proprietário do imóvel', on_delete=django.db.models.deletion.CASCADE, related_name='propimovel', to='proprietarios.proprietario', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Imóvel do proprietário',
                'verbose_name_plural': 'Imóveis do proprietário',
            },
        ),
    ]
