# Generated by Django 5.2 on 2025-05-21 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_delete_proprietariosimovel'),
        ('proprietarios', '0002_imoveisproprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveisproprietario',
            name='imovel',
            field=models.ForeignKey(help_text='Imóvel', on_delete=django.db.models.deletion.CASCADE, related_name='imovelprop', to='imoveis.imovel', verbose_name='Imovel'),
        ),
        migrations.AlterField(
            model_name='imoveisproprietario',
            name='proprietario',
            field=models.ForeignKey(help_text='Nome do proprietario', on_delete=django.db.models.deletion.PROTECT, related_name='proprietarioimov', to='proprietarios.proprietario', verbose_name='Proprietario'),
        ),
    ]
