# Generated by Django 5.2 on 2025-05-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietarios', '0003_alter_imoveisproprietario_imovel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imoveisproprietario',
            unique_together={('proprietario', 'id')},
        ),
    ]
