# Generated by Django 5.2 on 2025-05-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_delete_proprietariosimovel'),
        ('proprietarios', '0004_alter_imoveisproprietario_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imoveisproprietario',
            unique_together={('proprietario', 'imovel')},
        ),
    ]
