# Generated by Django 5.2 on 2025-05-29 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietarios', '0005_alter_imoveisproprietario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveisproprietario',
            name='proprietario',
            field=models.ForeignKey(help_text='Nome do proprietario', on_delete=django.db.models.deletion.CASCADE, related_name='proprietarioimov', to='proprietarios.proprietario', verbose_name='Proprietario'),
        ),
    ]
