# Generated by Django 5.2 on 2025-07-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietarios', '0006_alter_imoveisproprietario_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='email',
            field=models.EmailField(help_text='Email completo do proprietário', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='fone',
            field=models.CharField(help_text='Celular completo do proprietário', max_length=15, unique=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='nome',
            field=models.CharField(help_text='Nome completo do proprietário', max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
