# Generated by Django 5.2 on 2025-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietarios', '0007_alter_proprietario_email_alter_proprietario_fone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='nome',
            field=models.CharField(help_text='Nome completo do proprietário', max_length=100, verbose_name='Nome'),
        ),
    ]
